# Generated by Django 4.1 on 2022-08-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('institution_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True, unique=True, verbose_name='email')),
                ('phone_number', models.IntegerField(default=-1)),
                ('creation_time', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
